import "~/styles/globals.css";

import { Inter } from "next/font/google";
import { ClerkProvider, UserButton } from "@clerk/nextjs";

import { TRPCReactProvider } from "~/trpc/react";
import Link from "next/link";
import { dark } from "@clerk/themes";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    // eslint-disable-next-line @typescript-eslint/no-unsafe-assignment, @typescript-eslint/no-explicit-any
    <ClerkProvider appearance={dark as any}>
      <html lang="en">
        <body className={`font-sans ${inter.variable}`}>
          <TRPCReactProvider>
            <div className="m-2 flex flex-row">
              <Link href="/" className="my-auto text-lg font-bold text-primary">
                Shared Timer
              </Link>
              <div className="flex-grow" />
              <UserButton />
            </div>
            {children}
          </TRPCReactProvider>
        </body>
      </html>
    </ClerkProvider>
  );
}

export const runtime = "edge";
